<?xml version="1.0" encoding="utf-8"?><Database Name="AWSS3DocsDB" Class="S3FileDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-5IFT3GP;Initial Catalog=AWSS3DocsDB;Integrated Security=True" SettingsObjectName="AWSS3DocScanner.Properties.Settings" SettingsPropertyName="AWSS3DocsDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AWSS3Object" Member="AWSS3Objects">
    <Type Name="AWSS3Object">
      <Column Name="FileID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FileKey" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FileName" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="FileModified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FileSize" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="WindowsFilePath" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="LastScanned" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>