#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWSS3DocScanner
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AWSS3DocsDB")]
	public partial class S3FileDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAWSS3Object(AWSS3Object instance);
    partial void UpdateAWSS3Object(AWSS3Object instance);
    partial void DeleteAWSS3Object(AWSS3Object instance);
    #endregion
		
		public S3FileDBDataContext() : 
				base(global::AWSS3DocScanner.Properties.Settings.Default.AWSS3DocsDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public S3FileDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public S3FileDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public S3FileDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public S3FileDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AWSS3Object> AWSS3Objects
		{
			get
			{
				return this.GetTable<AWSS3Object>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AWSS3Object")]
	public partial class AWSS3Object : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _FileID;
		
		private string _FileKey;
		
		private string _FileName;
		
		private System.Nullable<System.DateTime> _FileModified;
		
		private System.Nullable<long> _FileSize;
		
		private string _WindowsFilePath;
		
		private System.Nullable<System.DateTime> _LastScanned;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFileIDChanging(int value);
    partial void OnFileIDChanged();
    partial void OnFileKeyChanging(string value);
    partial void OnFileKeyChanged();
    partial void OnFileNameChanging(string value);
    partial void OnFileNameChanged();
    partial void OnFileModifiedChanging(System.Nullable<System.DateTime> value);
    partial void OnFileModifiedChanged();
    partial void OnFileSizeChanging(System.Nullable<long> value);
    partial void OnFileSizeChanged();
    partial void OnWindowsFilePathChanging(string value);
    partial void OnWindowsFilePathChanged();
    partial void OnLastScannedChanging(System.Nullable<System.DateTime> value);
    partial void OnLastScannedChanged();
    #endregion
		
		public AWSS3Object()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int FileID
		{
			get
			{
				return this._FileID;
			}
			set
			{
				if ((this._FileID != value))
				{
					this.OnFileIDChanging(value);
					this.SendPropertyChanging();
					this._FileID = value;
					this.SendPropertyChanged("FileID");
					this.OnFileIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileKey", DbType="VarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string FileKey
		{
			get
			{
				return this._FileKey;
			}
			set
			{
				if ((this._FileKey != value))
				{
					this.OnFileKeyChanging(value);
					this.SendPropertyChanging();
					this._FileKey = value;
					this.SendPropertyChanged("FileKey");
					this.OnFileKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="VarChar(255)")]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this.OnFileNameChanging(value);
					this.SendPropertyChanging();
					this._FileName = value;
					this.SendPropertyChanged("FileName");
					this.OnFileNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileModified", DbType="DateTime")]
		public System.Nullable<System.DateTime> FileModified
		{
			get
			{
				return this._FileModified;
			}
			set
			{
				if ((this._FileModified != value))
				{
					this.OnFileModifiedChanging(value);
					this.SendPropertyChanging();
					this._FileModified = value;
					this.SendPropertyChanged("FileModified");
					this.OnFileModifiedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileSize", DbType="BigInt")]
		public System.Nullable<long> FileSize
		{
			get
			{
				return this._FileSize;
			}
			set
			{
				if ((this._FileSize != value))
				{
					this.OnFileSizeChanging(value);
					this.SendPropertyChanging();
					this._FileSize = value;
					this.SendPropertyChanged("FileSize");
					this.OnFileSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WindowsFilePath", DbType="VarChar(255)")]
		public string WindowsFilePath
		{
			get
			{
				return this._WindowsFilePath;
			}
			set
			{
				if ((this._WindowsFilePath != value))
				{
					this.OnWindowsFilePathChanging(value);
					this.SendPropertyChanging();
					this._WindowsFilePath = value;
					this.SendPropertyChanged("WindowsFilePath");
					this.OnWindowsFilePathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastScanned", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastScanned
		{
			get
			{
				return this._LastScanned;
			}
			set
			{
				if ((this._LastScanned != value))
				{
					this.OnLastScannedChanging(value);
					this.SendPropertyChanging();
					this._LastScanned = value;
					this.SendPropertyChanged("LastScanned");
					this.OnLastScannedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
