#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentDB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DocumentDB")]
	public partial class DocsDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDocList(DocList instance);
    partial void UpdateDocList(DocList instance);
    partial void DeleteDocList(DocList instance);
    #endregion
		
		public DocsDBDataContext() : 
				base(global::DocumentDB.Properties.Settings.Default.DocumentDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DocsDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DocsDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DocsDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DocsDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DocList> DocLists
		{
			get
			{
				return this.GetTable<DocList>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DocList")]
	public partial class DocList : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DocID;
		
		private string _DocPath;
		
		private string _DocName;
		
		private System.DateTime _DocCreated;
		
		private System.Nullable<System.DateTime> _DocModified;
		
		private System.Nullable<long> _DocSize;
		
		private System.Nullable<System.DateTime> _LastScanned;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDocIDChanging(int value);
    partial void OnDocIDChanged();
    partial void OnDocPathChanging(string value);
    partial void OnDocPathChanged();
    partial void OnDocNameChanging(string value);
    partial void OnDocNameChanged();
    partial void OnDocCreatedChanging(System.DateTime value);
    partial void OnDocCreatedChanged();
    partial void OnDocModifiedChanging(System.Nullable<System.DateTime> value);
    partial void OnDocModifiedChanged();
    partial void OnDocSizeChanging(System.Nullable<long> value);
    partial void OnDocSizeChanged();
    partial void OnLastScannedChanging(System.Nullable<System.DateTime> value);
    partial void OnLastScannedChanged();
    #endregion
		
		public DocList()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int DocID
		{
			get
			{
				return this._DocID;
			}
			set
			{
				if ((this._DocID != value))
				{
					this.OnDocIDChanging(value);
					this.SendPropertyChanging();
					this._DocID = value;
					this.SendPropertyChanged("DocID");
					this.OnDocIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocPath", DbType="VarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string DocPath
		{
			get
			{
				return this._DocPath;
			}
			set
			{
				if ((this._DocPath != value))
				{
					this.OnDocPathChanging(value);
					this.SendPropertyChanging();
					this._DocPath = value;
					this.SendPropertyChanged("DocPath");
					this.OnDocPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocName", DbType="VarChar(MAX)")]
		public string DocName
		{
			get
			{
				return this._DocName;
			}
			set
			{
				if ((this._DocName != value))
				{
					this.OnDocNameChanging(value);
					this.SendPropertyChanging();
					this._DocName = value;
					this.SendPropertyChanged("DocName");
					this.OnDocNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocCreated", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime DocCreated
		{
			get
			{
				return this._DocCreated;
			}
			set
			{
				if ((this._DocCreated != value))
				{
					this.OnDocCreatedChanging(value);
					this.SendPropertyChanging();
					this._DocCreated = value;
					this.SendPropertyChanged("DocCreated");
					this.OnDocCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocModified", DbType="DateTime")]
		public System.Nullable<System.DateTime> DocModified
		{
			get
			{
				return this._DocModified;
			}
			set
			{
				if ((this._DocModified != value))
				{
					this.OnDocModifiedChanging(value);
					this.SendPropertyChanging();
					this._DocModified = value;
					this.SendPropertyChanged("DocModified");
					this.OnDocModifiedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocSize", DbType="BigInt")]
		public System.Nullable<long> DocSize
		{
			get
			{
				return this._DocSize;
			}
			set
			{
				if ((this._DocSize != value))
				{
					this.OnDocSizeChanging(value);
					this.SendPropertyChanging();
					this._DocSize = value;
					this.SendPropertyChanged("DocSize");
					this.OnDocSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastScanned", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastScanned
		{
			get
			{
				return this._LastScanned;
			}
			set
			{
				if ((this._LastScanned != value))
				{
					this.OnLastScannedChanging(value);
					this.SendPropertyChanging();
					this._LastScanned = value;
					this.SendPropertyChanged("LastScanned");
					this.OnLastScannedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
